version: '3.8'

services:
  prod:
    image: chapters-frontend
    container_name: chapters-frontend
    build:
      context: ./
      target: production
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    # TODO: add the environment variables for the production environment
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_KEYCLOAK_URL=http://localhost:8080why